project_id = "achjbhxncobmcbnjyyat"

[functions.generate-site]
verify_jwt = false

[functions.get-published-site]
verify_jwt = false

[functions.verify-domain]
verify_jwt = false

[functions.manage-vercel-domain]
verify_jwt = false